/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pflic' at '3/15/17 7:59 PM' with Gradle 3.2.1
 *
 * @author pflic, @date 3/15/17 7:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
